### PR TITLE
added code to perform hab pkg export function

### LINKED ISSUE #1: Feature - Add Docker Export
It'd be sweet if we could add the ability to export Habitat packages into docker containers through this plugin. Currently, I'm calling the native shell {bash, powershell} to execute the command with

  \\$new_pkg="${workspace}/results/${env.PKG_FILE_NAME}"
  hab pkg export docker \\$new_pkg

It'd be great to perform this process automagically through the plugin with a 

  habitat task: 'export', format: 'docker', lastBuildFile: "${workspace}/results/last_build.env"

I'd be happy to help if you point me to an example of calling the shell commands in the code for the plugin

### PR DESCRIPTION
**Pull request by ktraister**
Added a couple functions for hab pkg export function (setFormat, getFormat)
Added case for export
Added exportCommand function 
   - please make sure I got the array instantiation and checking for format string correct (line 170-175)

Please let me know if I missed anything!

resolves #1

### CODE REVIEW

**Review by skylerto — CHANGES_REQUESTED** [review]
Awesome work!

Looks like the formatting is a bit off, which editor are you using, Intellij?

**Comment by ktraister** [comment]
I use vim with plugins for whatever language I'm writing, a java plugin in this case. If you point out where the formatting got weird I'll get a new commit on this pull request

**Comment by skylerto** [comment]
I love it. I mostly use neovim except for java things. :(

Were you able to test this locally?

**Comment by ktraister** [comment]
I haven't done any testing on the plugin code. I tried using "javac" to compile the package, but I was getting like 56 compile errors on master, so the best I could do was get my branch to the same point and get it to pass your integration tests. Is there a framework you can recommend for testing the plugin locally?

**Comment by skylerto** [comment]
Yeah javac would totally give you errors, you'll need to use maven, E.g.

```
$ mvn clean install
```

ref: https://maven.apache.org/what-is-maven.html

**Review by skylerto — APPROVED** [review]
There are no compilation errors, and the code looks good to me so I'll merge and update the formatting on master.

Thanks for the contribution!

**Comment by skylerto** [comment]
release [habitat-0.3.1](https://github.com/jenkinsci/habitat-plugin/releases/tag/habitat-0.3.1) is available on update centre. :)

**Pull request merged**
