### PR TITLE
Added more functionality to plugin

### PR DESCRIPTION
**Pull request by ktraister**
Added channels, config, demote, search, exec, and binlink commands to the plugin
Builds passed using maven, but no testing has been done on the plugin as of yet

### CODE REVIEW

**Comment by ktraister** [comment]
I was going to test this plugin on our dev cluster, but it appears that this has been torn down. Do you do any testing on the artifacts from a maven build before you slap it into the Jenkins Plugin repo?

**Comment by skylerto** [comment]
I do usually do some testing, if you do `mvn hpi:run` it will spin up jenkins locally with the plugin installed and you can do some basic local testing.

ref: https://wiki.jenkins.io/display/JENKINS/Plugin+tutorial

**Comment by skylerto** [comment]
This is an awesome contribution, I'd love to see some usage documentation.

**Comment by ktraister** [comment]
Awesome, thanks for the tip! I'll do some of that here in a few minutes. 

I was also thinking about what I could do for documentation, not sure if you want to do all the documentation in SCM or if you'd rather switch to GitHub's build-in wiki. The documentation on the plugin is pretty sparse, and I think I could greatly improve it for established and new features.

**Comment by skylerto** [comment]
I'm a fan of README docs.

I'm not looking at anything specific, maybe just a few Jenkinsfile with example builds.

I do need to update the docs for sure, I'm pretty sure that the state that it's in right now won't work. 👎

**Comment by ktraister** [comment]
Commits incoming...

Commit added, please take a look

**Review by skylerto — APPROVED** [review]
Thanks for the contribution!

**Comment by ktraister** [comment]
Made a few updates to the readme, should be set to pull now

**Review by skylerto — APPROVED** [review]

**Pull request merged**
